CREATE TABLE IF NOT EXISTS UND_SYSTEM_USER (
    ID_SYSTEM_USER INT PRIMARY KEY AUTO_INCREMENT,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR(200) NOT NULL

);

CREATE TABLE IF NOT EXISTS UND_SYSTEM_ROLES (
    ID_SYSTEM_ROLES INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(20) NOT NULL UNIQUE,
    DESCRIPTION VARCHAR(200)
);

CREATE TABLE IF NOT EXISTS UND_SYSTEM_USER_ROLES (
    ID_SYSTEM_USER INT NOT NULL,
    ID_SYSTEM_ROLES INT NOT NULL,

    FOREIGN KEY (ID_SYSTEM_USER)
    REFERENCES UND_SYSTEM_USER(ID_SYSTEM_USER),

    FOREIGN KEY (ID_SYSTEM_ROLES)
    REFERENCES UND_SYSTEM_ROLES(ID_SYSTEM_ROLES)
);


INSERT INTO UND_SYSTEM_USER (USERNAME, PASSWORD) VALUES ('admin', '$2a$10$2O6fn.Lm5szdonRjxOzdDueZzqXTKgtzv49x4QIJoFcbTBIt9gJJ6');
INSERT INTO UND_SYSTEM_ROLES (NAME, DESCRIPTION) VALUES ('ROLE_ADMIN', 'ADMNISTRADOR DO SISTEMA');
INSERT INTO UND_SYSTEM_ROLES (NAME, DESCRIPTION) VALUES ('ROLE_BASIC', 'QUALQUER USUÁRIO DO SISTEMA');

INSERT INTO UND_SYSTEM_USER_ROLES (ID_SYSTEM_USER, ID_SYSTEM_ROLES) VALUES (1, 1);
INSERT INTO UND_SYSTEM_USER_ROLES (ID_SYSTEM_USER, ID_SYSTEM_ROLES) VALUES (1, 2);